substitutions:
  name: jnge-g-series
  tx_pin: GPIO4
  rx_pin: GPIO5

esphome:
  name: ${name}
  min_version: 2024.6.0

esp8266:
  board: d1_mini

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

ota:
  platform: esphome

logger:
  level: DEBUG

api:
  reboot_timeout: 0s

uart:
  id: uart_0
  baud_rate: 9600
  tx_pin: ${tx_pin}
  rx_pin: ${rx_pin}
  debug:
    direction: BOTH
    dummy_receiver: true
    after:
      # 100ms ... 750ms
      timeout: 100ms

interval:
  - interval: 5s
    then:
      - uart.write: [0x06, 0x16, 0x10, 0x24, 0x00, 0x27, 0x4D, 0x6F]

      - delay: 2s

      - uart.write: [0x06, 0x12, 0x10, 0x00, 0x00, 0x24, 0xBC, 0xA5]
