substitutions:
  name: jn-g
  status: "${name} status"
  config: "${name} config"
  device_description: "Monitor a JN-G series inverter via RS485 (Modbus)"
  external_components_source: github://syssi/esphome-jnge-mppt-controller@main
  tx_pin: GPIO4
  rx_pin: GPIO5

esphome:
  name: ${name}
  comment: ${device_description}
  min_version: 2024.6.0
  project:
    name: "syssi.esphome-jnge-mppt-controller"
    version: 1.2.0

esp8266:
  board: d1_mini

external_components:
  - source: ${external_components_source}
    refresh: 0s

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

ota:
  platform: esphome

logger:
  level: DEBUG

api:

uart:
  baud_rate: 9600
  tx_pin: ${tx_pin}
  rx_pin: ${rx_pin}
  debug:
    direction: BOTH

jnge_g_series:
  id: jnge0
  update_interval: 2s

sensor:
  - platform: jnge_g_series
    ac_voltage1:
      name: "${status} AC voltage1"
    ac_voltage2:
      name: "${status} AC voltage2"
    ac_frequency:
      name: "${status} AC frequency"
    battery_voltage:
      name: "${status} battery voltage"
    total_energy:
      name: "${status} total energy"
    inverter_temperature:
      name: "${status} inverter temperature"
